# ~/ansible/playbooks/playbook.yml
- hosts: ansible_hosts
  tasks:
    - name: Установка Python
      apt:
        name: python3
        state: present
      become: true  

    - name: Установка PIP
      apt:
        name: python3-pip
        state: present
      become: true
